# Generated by Django 5.0 on 2023-12-12 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_products', '0007_sale'),
        ('app_users', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('deliveryType', models.CharField(default='', max_length=128, verbose_name='Delivery type')),
                ('paymentType', models.CharField(default='', max_length=128, verbose_name='Payment type')),
                ('totalCost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total cost')),
                ('status', models.CharField(default='', max_length=128, verbose_name='Status')),
                ('city', models.CharField(default='', max_length=256, verbose_name='City')),
                ('address', models.CharField(default='', max_length=256, verbose_name='Address')),
                ('products', models.ManyToManyField(related_name='orders', to='app_products.product', verbose_name='Products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='app_users.userprofile', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
