# Generated by Django 5.0 on 2023-12-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_products", "0002_categoryicon"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=128, unique=True)),
            ],
        ),
    ]
